#!/usr/bin/env python3
"""Synthetic read_paths regression, both providers; never launch agents or tmux.

REVIEWER_READ_PATHS_TEST_CODEX_SCRIPTS / _CLAUDE_SCRIPTS can select original
script trees for regression evidence without stashing the shared checkout.
"""
import argparse
import importlib.util
import json
import os
from pathlib import Path
import shlex
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
ENV = {k: v for k, v in os.environ.items() if not k.startswith(("SESSION_", "KNOWLEDGE_")) and k not in ("TMUX", "TMUX_PANE")}
IDENTITY = "SESSION_WORKSPACE_READ_PATHS_JSON"


class ReadPaths:
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix="read-paths-", dir="/tmp")
        self.root = Path(self.tmp.name).resolve() / "project"
        self.external = self.root.parent / "external"
        for d in ("component-a", "component-b", "docs", "docs-extra", ".agent-workspace", ".tmp/messages", ".agents/memory"):
            (self.root / d).mkdir(parents=True)
        self.external.mkdir()
        for p in ("AGENTS.md", "other.md", "docs/a.md", "docs/with space.md", "docs-extra/no.md", "component-a/a.md", "component-b/b.md", ".agents/memory/MEMORY.md"):
            (self.root / p).write_text("sample\n")
        (self.external / "README.md").write_text("external\n")
        self.cfg = json.loads((self.scripts / "fixtures/valid/harness-v2.json").read_text())
        if self.provider == "claude":
            self.cfg["runtimes"] = {"claude": {"program": "claude", "args": []}}
            for role in self.cfg["roles"].values():
                role["runtime"] = "claude"
        for i, p in enumerate(self.cfg["sessions"][0]["panes"]):
            p["name"] = ("master", "executor", "reviewer")[i]
        self.pane = self.cfg["sessions"][0]["panes"][2]
        self.path = self.root / ".agent-workspace/workspace.json"
        self.env = dict(ENV, HOME=str(self.root.parent / "home"), CLAUDE_HOME=str(self.root.parent / "home/.claude"),
                        CLAUDE_CONFIG_DIR=str(self.root.parent / "home/.claude"), CODEX_HOME=str(self.root.parent / "home/.codex"),
                        TMUX_TMPDIR=str(self.root.parent))
        self.write()

    def tearDown(self):
        self.tmp.cleanup()

    def write(self):
        self.path.write_text(json.dumps(self.cfg))

    def script(self, name, *args, env=None):
        return subprocess.run(["bash", str(self.scripts / (name + ".sh")), *args, "--config", str(self.path)],
                              capture_output=True, text=True, env=env or self.env, timeout=40)

    def plan(self):
        self.write()
        r = self.script("workspace-plan", "--json")
        self.assertEqual(r.returncode, 0, r.stderr)
        return json.loads(r.stdout)

    def launch(self, name="reviewer"):
        self.write()
        r = self.script("adapters", "env-exports", "--pane", name)
        self.assertEqual(r.returncode, 0, r.stderr)
        # Only execute exports generated by the actual adapter from synthetic
        # config; no agent, secrets or real coordination stores are involved.
        r = subprocess.run(["bash", "-c", 'eval "$1"; env -0', "exports", r.stdout], env=self.env, capture_output=True, timeout=40)
        self.assertEqual(r.returncode, 0, r.stderr)
        return dict(v.decode().split("=", 1) for v in r.stdout.split(b"\0") if v)

    def decision(self, command="cat ../docs/a.md", env=None, tool="Bash", inputs=None):
        env = self.launch() if env is None else env
        payload = {"tool_name": tool, "tool_input": inputs if inputs is not None else {"command": command}}
        r = subprocess.run([sys.executable, str(self.scripts / "harness-policy.py"), "--decision-json"],
                           input=json.dumps(payload), text=True, capture_output=True, env=env, timeout=40)
        self.assertEqual(r.returncode, 0, r.stderr)
        return json.loads(r.stdout)

    def assert_decision(self, expected, command="cat ../docs/a.md", **kwargs):
        d = self.decision(command, **kwargs)
        self.assertEqual(d["decision"], expected, (command, d))
        return d

    def test_default_and_empty_compatibility(self):
        before = self.plan()
        env = self.launch()
        env.pop(IDENTITY, None)  # previous launcher, no opt-in feature
        self.assert_decision("allow", "cat a.md", env=env)
        self.assert_decision("deny", env=env)
        self.pane["read_paths"] = []
        self.assertEqual(self.plan(), before)
        self.assertEqual(self.launch().get(IDENTITY, ""), "")

    def test_reads_and_argv_isolation(self):
        before = self.script("adapters", "agent-argv", "--pane", "reviewer").stdout
        self.pane["read_paths"] = ["docs", "AGENTS.md", "component-b", str(self.external)]
        plan = self.plan()
        paths = plan["sessions"][0]["panes"][2]["read_paths"]
        self.assertEqual(len(paths), 4)
        self.assertIn({"path": str(self.root / "AGENTS.md"), "kind": "file"}, paths)
        self.assertEqual(self.script("adapters", "agent-argv", "--pane", "reviewer").stdout, before)
        env = self.launch()
        self.assertEqual(env[IDENTITY], json.dumps(paths, sort_keys=True, separators=(",", ":")))
        for cmd in ("cat ../docs/a.md", "cat '../docs/with space.md'", "cat ../AGENTS.md", "cat ../component-b/b.md",
                    "cat " + shlex.quote(str(self.external / "README.md")), "rg sample ../docs", "git -C ../component-b status"):
            self.assert_decision("allow", cmd, env=env)
        for cmd in ("cat ../other.md", "ls ..", "cat ../docs-extra/no.md", "cat ../docs/../other.md"):
            self.assert_decision("deny", cmd, env=env)
        self.assert_decision("allow", tool="exec_command", inputs={"command": ["cat", "../docs/a.md"]}, env=env)
        self.assert_decision("allow", inputs={"command": "cat a.md", "cwd": str(self.root / "docs")}, env=env)
        self.assert_decision("deny", inputs={"command": "cat other.md", "cwd": str(self.root)}, env=env)
        self.assert_decision("deny", env=self.launch("executor"))
        pinned = self.script("adapters", "session-env", "--pane", "reviewer")
        self.assertEqual(pinned.returncode, 0, pinned.stderr)
        self.assertNotIn(IDENTITY, pinned.stdout)

    def test_file_not_directory_authority(self):
        self.pane["read_paths"] = ["docs/a.md"]
        env = self.launch()
        self.assert_decision("allow", env=env)
        for cmd in ("ls ../docs", "cat '../docs/with space.md'", "cat ../docs/a.md/child"):
            self.assert_decision("deny", cmd, env=env)

    def test_writes_and_staging(self):
        self.pane["read_paths"] = ["docs"]
        env = self.launch()
        self.assert_decision("allow", env=env)
        for cmd in ("touch ../docs/new.md", "echo text > ../docs/a.md", "git -C ../docs add a.md"):
            self.assert_decision("deny", cmd, env=env)
        self.assert_decision("deny", tool="Write", inputs={"file_path": str(self.root / "docs/a.md"), "content": "change"}, env=env)
        self.assert_decision("allow", tool="Write", inputs={"file_path": str(self.root / ".tmp/messages/report.md"), "content": "report"}, env=env)

    def test_validation(self):
        self.pane["read_paths"] = ["docs", "AGENTS.md", str(self.external)]
        self.plan()  # control before hostile cases
        (self.root / "alias").symlink_to(self.root / "docs")
        os.mkfifo(self.root / "fifo")
        cases = [None, "docs", [3], [""], [" docs"], ["docs\n"], ["docs/*"], ["${NO_SUCH_VAR}"], ["`pwd`"], ["~"], ["-x"],
                 [".."], ["../external"],
                 ["docs", "docs/a.md"], ["docs", "docs"], ["docs"] * 17, ["."], [".tmp/messages"], [".agents/memory/MEMORY.md"],
                 ["/"], [str(self.root.parent / "home")]]
        (self.root.parent / "home").mkdir()
        for paths in cases:
            with self.subTest(paths=paths):
                self.pane["read_paths"] = paths
                self.write()
                r = self.script("workspace-plan", "--json")
                self.assertNotEqual(r.returncode, 0, paths)
                self.assertIn("read_paths", r.stderr)
        self.pane["read_paths"] = ["docs"]
        self.plan()
        for path in ("missing", "fifo", "alias", "alias/a.md", str(self.root / "alias")):
            self.pane["read_paths"] = [path]
            plan = self.plan()
            self.assertEqual(plan["sessions"][0]["panes"][2]["read_paths"][0]["kind"], "unavailable")
            launch = self.script("adapters", "env-exports", "--pane", "reviewer")
            self.assertNotEqual(launch.returncode, 0)
            self.assertIn("unavailable read_paths", launch.stderr)

    def test_roles_and_identity_override_validation(self):
        self.pane["read_paths"] = ["docs"]
        self.plan()
        for role in ("master", "executor"):
            self.pane.pop("read_paths")
            target = next(p for p in self.cfg["sessions"][0]["panes"] if p["role"] == role)
            target["read_paths"] = ["docs"]
            self.write()
            self.assertNotEqual(self.script("workspace-plan", "--json").returncode, 0)
            target.pop("read_paths")
            self.pane["read_paths"] = ["docs"]
        self.cfg["harness"]["enabled"] = False
        self.write()
        self.assertNotEqual(self.script("workspace-plan", "--json").returncode, 0)
        self.cfg["harness"]["enabled"] = True
        for target, value in ((self.cfg["env"]["groups"]["dev"]["values"], {IDENTITY: "spoof"}),):
            target.update(value)
            self.write()
            self.assertNotEqual(self.script("workspace-plan", "--json").returncode, 0)
            target.clear()
        self.cfg["env"]["pane_name_aliases"] = [IDENTITY]
        self.write()
        self.assertNotEqual(self.script("workspace-plan", "--json").returncode, 0)

    def test_symlinks_and_recursive_controls(self):
        self.pane["read_paths"] = ["docs"]
        (self.root / "docs/out").symlink_to(self.root / "other.md")
        (self.root / "docs/in").symlink_to(self.root / "docs/a.md")
        env = self.launch()
        for cmd in ("cat ../docs/in", "rg sample ../docs", "grep -r sample ../docs", "find ../docs -type f", "diff a.md ../docs/a.md"):
            self.assert_decision("allow", cmd, env=env)
        for cmd in ("cat ../docs/out", "rg -L sample ../docs", "rg -nL sample ../docs", "rg --follow sample ../docs", "grep -Rn sample ../docs",
                    "grep --dereference-recursive sample ../docs", "grep -rS sample ../docs", "grep -S -r sample ../docs", "grep --dereference-files -r sample ../docs", "find -L ../docs", "find ../docs -follow", "du -L ../docs", "ls -LR ../docs",
                    "diff -r ../docs .", "diff ../docs ."):
            d = self.assert_decision("deny", cmd, env=env)
            self.assertIn(d["rule"], ("reviewer.path", "reviewer.symlink_follow"))

    def test_recursive_floor_without_new_config(self):
        env = self.launch()
        for cmd in ("rg sample .", "grep --recursive sample .", "find . -type f", "diff a.md a.md"):
            self.assert_decision("allow", cmd, env=env)
        for cmd in ("rg -L sample .", "grep -Rn sample .", "find -L .", "du -L .", "ls -LR .", "diff . ."):
            with self.subTest(command=cmd):
                self.assert_decision("deny", cmd, env=env)

    def test_workdir_operand_base(self):
        self.pane["read_paths"] = [str(self.external)]
        (self.external / "leak").symlink_to(self.root / "other.md")
        env = self.launch()
        self.assert_decision("allow", "cat a.md", env=env)
        self.assert_decision("deny", "cat " + str(self.external / "leak"), env=env)
        for field in ("cwd", "workdir"):
            self.assert_decision("allow", inputs={"command": "cat README.md", field: str(self.external)}, env=env)
            for command in ("cat leak", "cat ../project/other.md", "cat ./leak"):
                self.assert_decision("deny", inputs={"command": command, field: str(self.external)}, env=env)
        self.assert_decision("deny", inputs={"command": "cat README.md", "cwd": str(self.external), "workdir": str(self.root / "component-a")}, env=env)

    def policy_module(self):
        spec = importlib.util.spec_from_file_location("read_paths_policy", self.scripts / "harness-policy.py")
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module

    def test_helpers_do_not_gain_store_authority(self):
        self.pane["read_paths"] = ["docs"]
        env = self.launch()
        policy = self.policy_module()
        with patch.dict(os.environ, env, clear=True):
            ctx, failure = policy.load_context()
            self.assertIsNone(failure)
            self.assertEqual(policy.take_knowledge_store(ctx, ["--store", str(self.root / "component-a"), "query"]), ["query"])
            with self.assertRaises(policy.PolicyFailure):
                policy.take_knowledge_store(ctx, ["--store", str(self.root / "docs"), "query"])
            self.assertTrue(policy.reviewer_readable(ctx, self.root / "docs/a.md"))
            self.assertFalse(policy.readable(ctx, self.root / "docs/a.md"))

    def test_diagnostics(self):
        self.pane["read_paths"] = ["docs"]
        env = self.launch()
        r = self.script("harness-status", "--json", env=env)
        self.assertEqual(r.returncode, 0, r.stderr)
        status = json.loads(r.stdout)
        self.assertTrue(status["identity"]["matches"])
        self.assertEqual(status["read_paths"], json.loads(env[IDENTITY]))
        stale = dict(env, **{IDENTITY: ""})
        r = self.script("harness-status", "--json", env=stale)
        status = json.loads(r.stdout)
        self.assertFalse(status["identity"]["matches"])
        self.assertEqual(status["policy"]["rule"], "identity.read_paths")
        # doctor also checks actual hook installation, which is intentionally
        # absent in these synthetic homes; inspect the decisive live check.
        report = json.loads(self.script("harness-doctor", "--json", env=stale).stdout)
        live = next(c for c in report["checks"] if c["id"] == "identity.live")
        self.assertEqual(live["status"], "ERROR")

    def test_v5_environment_boundaries(self):
        spec = importlib.util.spec_from_file_location("read_paths_env_fixture", self.scripts / "test-environments.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        self.cfg = module.config()
        for directory in ("control-web", "control-vue3", ".tmp/scheduler/tasks", ".tmp/integrations"):
            (self.root / directory).mkdir(parents=True, exist_ok=True)
        self.pane = self.cfg["sessions"][1]["panes"][2]
        self.pane["read_paths"] = ["docs", str(self.external)]
        self.plan()
        for path in ("component-b", "control-vue3", str(self.root / "component-b")):
            self.pane["read_paths"] = [path]
            self.write()
            r = self.script("workspace-plan", "--json")
            self.assertNotEqual(r.returncode, 0, path)
            self.assertIn("another environment", r.stderr)

    def test_protected_overlap(self):
        self.pane["read_paths"] = ["docs"]
        self.plan()
        # Test the resolver directly so credential fixtures need no Git repo,
        # secret-file permissions or actual provider configuration.
        spec = importlib.util.spec_from_file_location("read_paths_resolver", self.scripts / "reviewer-read-paths.py")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        with patch.dict(os.environ, self.env, clear=True):
            for field in ("secret", "override", "memory", "provider"):
                original = json.loads(json.dumps(self.cfg))
                self.assertTrue(module.resolve_paths(self.cfg, self.root))
                if field == "secret":
                    self.cfg["secrets"] = {"env_file": "docs/a.md"}
                elif field == "override":
                    self.cfg["stores"]["overrides"] = {"contexts": "docs"}
                elif field == "memory":
                    self.cfg["stores"]["memory"]["root"] = "docs"
                else:
                    os.environ["CODEX_HOME"] = str(self.root / "docs")
                with self.assertRaisesRegex(ValueError, "protected"):
                    module.resolve_paths(self.cfg, self.root)
                self.cfg = original

    def test_drift_both_modes(self):
        for mode in ("audit", "enforce"):
            self.cfg["harness"]["mode"] = mode
            self.pane["read_paths"] = ["docs/a.md"]
            env = self.launch()
            self.assert_decision("allow", env=env)
            self.assert_decision("audit" if mode == "audit" else "deny", "cat ../other.md", env=env)
            missing = dict(env)
            missing.pop(IDENTITY)
            self.assertEqual(self.assert_decision("deny", env=missing)["rule"], "identity.read_paths")
            self.pane["read_paths"] = ["AGENTS.md"]
            self.write()
            self.assertEqual(self.assert_decision("deny", env=env)["rule"], "identity.read_paths")
            self.pane["read_paths"] = []
            self.write()
            self.assertEqual(self.assert_decision("deny", env=env)["rule"], "identity.read_paths")
            self.pane["read_paths"] = ["docs/a.md"]
            self.write()
            target = self.root / "docs/a.md"
            target.unlink()
            self.assertEqual(self.assert_decision("deny", env=env)["rule"], "identity.read_paths")
            target.mkdir()
            self.assertEqual(self.assert_decision("deny", env=env)["rule"], "identity.read_paths")
            target.rmdir()
            target.symlink_to(self.root / "other.md")
            self.assertEqual(self.assert_decision("deny", env=env)["rule"], "identity.read_paths")
            target.unlink()
            target.write_text("sample\n")
            self.assert_decision("allow", env=env)

    def test_unavailable_paths_do_not_block_other_panes_or_stop(self):
        self.cfg["behavior"]["session_chat_helper"] = {"on_missing": "warn"}
        self.pane["read_paths"] = ["docs/a.md"]
        envs = {name: self.launch(name) for name in ("reviewer", "executor", "master")}
        self.assert_decision("allow", env=envs["reviewer"])
        target = self.root / "docs/a.md"
        for state in ("missing", "symlink", "fifo"):
            target.unlink()
            if state == "symlink":
                target.symlink_to(self.root / "other.md")
            elif state == "fifo":
                os.mkfifo(target)
            plan = self.plan()
            entry = plan["sessions"][0]["panes"][2]["read_paths"][0]
            self.assertEqual(entry["kind"], "unavailable")
            self.assertEqual(entry["path"], str(target))
            self.assert_decision("deny", env=envs["reviewer"])
            self.assert_decision("allow", "cat a.md", env=envs["executor"])
            self.assert_decision("allow", "pwd", env=envs["master"])
            for action, args in (("workspace-status", ("--json",)), ("workspace-stop", ("--confirmed", "--no-save"))):
                result = self.script(action, *args)
                self.assertEqual(result.returncode, 0, (action, result.stderr))
                if action == "workspace-status":
                    row = next(r for r in json.loads(result.stdout) if r["pane"] == "reviewer")
                    self.assertEqual(row["read_paths"][0]["kind"], "unavailable")
            for action, args in (("workspace-start", ("--no-agents", "--no-services", "--no-attach")),
                                 ("workspace-restart", ("--no-save", "--no-agents", "--no-services", "--no-attach")),
                                 ("workspace-reconcile", ("--apply", "--adopt", "--confirmed"))):
                result = self.script(action, *args)
                self.assertNotEqual(result.returncode, 0, action)
                self.assertIn("unavailable read_paths", result.stderr)
            sessions = subprocess.run(["tmux", "list-sessions"], env=self.env, text=True, capture_output=True)
            self.assertNotEqual(sessions.returncode, 0, sessions.stdout)
            if target.exists() or target.is_symlink():
                target.unlink()
            target.write_text("sample\n")
            self.assert_decision("allow", env=envs["reviewer"])


def suite(provider_filter=None):
    tests = unittest.TestSuite()
    for provider, prefix in (("codex", "codex/plugins"), ("claude", "plugins")):
        if provider_filter and provider != provider_filter:
            continue
        scripts = Path(os.environ.get("REVIEWER_READ_PATHS_TEST_" + provider.upper() + "_SCRIPTS", str(ROOT / prefix / "session-workspace/scripts")))
        cls = type(provider.title() + "ReadPaths", (ReadPaths, unittest.TestCase), {"scripts": scripts, "provider": provider})
        tests.addTests(unittest.defaultTestLoader.loadTestsFromTestCase(cls))
    return tests


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--provider", choices=("codex", "claude"))
    sys.exit(not unittest.TextTestRunner(verbosity=2).run(suite(parser.parse_args().provider)).wasSuccessful())
